nom : Pylint

sur : [push]

emplois :
  construire :
    fonctionne-sur : ubuntu-latest
    stratégie :
      matrice :
        python-version : ["3.8", "3.9", "3.10"]
    étapes :
    - utilise : actions/checkout@v4
    - nom : Configurer Python ${{ matrix.python-version }}
      utilise : actions/setup-python@v3
      avec :
        python-version : ${{ matrix.python-version }}
    - nom : Installer les dépendances
      run : |
        python -m pip install --upgrade pip
        pip install pylint
    - nom : Analyse du code avec pylint
      run : |
        pylint $(git ls-files '*.py')


